# Generated by Django 4.0.5 on 2022-09-01 22:07

import datetime
from django.db import migrations, models
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='create_date',
        ),
        migrations.AddField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 1, 22, 7, 0, 503056, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='create_data',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
